### ISSUE TITLE
Rename github repository

### ISSUE THREAD

**Issue by manthey** [OpenGeoscience/database_assetstore#25]
It seems like this repository should be renamed from `girder_db_items` to `database_assetstore`.  I think that @ronichoudhury, @aashish24, and @dorukozturk are using it, so I'd like to make sure this won't break their process too badly if it is renamed.

**Comment by ronichoudhury** [comment]
My process involves Ansible cloning this repository into Girder's `plugins` directory, using `database_assetstore` as the name of the cloned directory. In other cases I clone the directory by hand (omitting the rename bit by force of habit) then symlinking it to `database_assetstore` in the plugins directory. In both cases, renaming this repo would be welcome.

**Comment by jeffbaumes** [comment]
I think the renaming makes sense for the plugin as it stands, but @zachmullen's comment in Girder (https://github.com/girder/girder/pull/1559#issuecomment-244990293) makes me think there first needs to be a discussion of where this is headed, or else another rename may be required.

**Comment by manthey** [comment]
Done.  Another rename may be required, but github will handle the redirection, so it shouldn't be a big deal.
