### ISSUE TITLE
girder install plugin step fails for postgres only installation

### ISSUE THREAD

**Issue by aashish24** [OpenGeoscience/database_assetstore#44]
``girder-install plugin -s database_assetstore``

results in (for Minerva)

 Downloading mysqlclient-1.3.12.tar.gz (89kB)
    100% |████████████████████████████████| 92kB 1.8MB/s
    Complete output from command python setup.py egg_info:
    sh: mysql_config: command not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/53/trp_hw7d3w5194x46t8x84jw0000gn/T/pip-build-SJ2vWs/mysqlclient/setup.py", line 17, in <module>
        metadata, options = get_config()
      File "setup_posix.py", line 44, in get_config
        libs = mysql_config("libs_r")
      File "setup_posix.py", line 26, in mysql_config
        raise EnvironmentError("%s not found" % (mysql_config.path,))
    EnvironmentError: mysql_config not found

**Comment by manthey** [comment]
We don't currently have the prerequisites listed anywhere, and the python requirements.txt installs all libraries, though some can be option.  As future work, we can add a setup.py file with extras_require which would then necessitate installing via a command like
```
  girder-install plugin -s database_assetstore
  pip install .[mysql,postgres,sqlite]
```
where the last line you would only list those databases that you want to support.

**Comment by aashish24** [comment]
> Did you install the mysql client library (on a recent Ubuntu you can use apt-get install mysql-client)?

after I ran into this issue. I did. It would be nice to have it optional (if we are not using mysql).

**Comment by aashish24** [comment]
> where the last line you would only list those databases that you want to support.

this would be very nice.

**Comment by matthewma7** [comment]
When I was testing stuff with clean Ubuntu 16, I encountered this exact error.
I don't know what does this line do 
**sudo apt-get install libgdal-dev libnetcdf-dev libpng12-dev pkg-config**
It doesn't seem has something to do with mysql to me, but this line from [our documentation](https://github.com/Kitware/minerva/blob/master/docs/installation.rst#ubuntu-1404) solved the problem.
